version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: digi-dose-client
    ports:
      - "5173:5173"
    depends_on:
      - server
    

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: digi-dose-server
    ports:
      - "5000:5000"
